<?php

function unccd_event_map_theme($existing, $type, $theme, $path) {
    return [
        'map_view' => [
            'variables' => [
                'events' => [],
            ],
        ],
        'events_around_the_world' => [
            'variables' => [
                'events' => [],
            ],
        ],
        'form_view' => [
            'variables' => [
                'form' => '',
            ],
        ],
    ];
}

